In [7]:

import numpy as np
import torch

In [3]:
mu_list=[[1,2,3,4],[6,7,9,9]]

In [5]:
mu_list

[[1, 2, 3, 4], [6, 7, 9, 9]]

In [8]:
np1=np.random.rand(3,4)
np1

array([[0.99707498, 0.50111978, 0.27920326, 0.00701054],
       [0.43725975, 0.22141853, 0.01104932, 0.95690997],
       [0.74821052, 0.38756586, 0.59541648, 0.1999587 ]])

In [10]:
tensor_2d=torch.randn(3,4)
tensor_2d

tensor([[-1.2595, -0.0861,  1.4275,  1.3339],
        [-1.5141, -1.2944, -1.3561, -0.8420],
        [ 0.9619, -0.6814, -1.0444,  0.7775]])

In [11]:
tensor_3d=torch.zeros(2,3,4)
tensor_3d

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [12]:
#create tensor out of mumpy array
my_tensor=torch.tensor(np1)
my_tensor

tensor([[0.9971, 0.5011, 0.2792, 0.0070],
        [0.4373, 0.2214, 0.0110, 0.9569],
        [0.7482, 0.3876, 0.5954, 0.2000]], dtype=torch.float64)