In [13]:
import torch

In [14]:
my_torch=torch.arange(10)
my_torch

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
my_torch.reshape(5,2)

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [16]:
my_torch.view(2,5)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [18]:
my_torch.reshape(2,5)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [19]:
my_torch

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
my_torch2=my_torch.reshape(5,2)

In [21]:
my_torch2

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [23]:
my_torch2[:,1]

tensor([1, 3, 5, 7, 9])