<a href="https://colab.research.google.com/github/Sanj-bot/pytorch/blob/main/t4updated.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [2]:
import numpy as np

In [3]:
tensor_a=torch.tensor([1,2,3,4])
tensor_b=torch.tensor([5,6,7,8])
tensor_a+tensor_b

tensor([ 6,  8, 10, 12])

In [4]:
torch.add(tensor_a,tensor_b)

tensor([ 6,  8, 10, 12])

In [5]:
tensor_a-tensor_b

tensor([-4, -4, -4, -4])

In [6]:
torch.sub(tensor_a,tensor_b)

tensor([-4, -4, -4, -4])

In [7]:
tensor_a*tensor_b

tensor([ 5, 12, 21, 32])

In [8]:
torch.mul(tensor_a,tensor_b)

tensor([ 5, 12, 21, 32])

In [9]:
tensor_a/tensor_b

tensor([0.2000, 0.3333, 0.4286, 0.5000])

In [10]:
torch.div(tensor_a,tensor_b)

tensor([0.2000, 0.3333, 0.4286, 0.5000])

In [11]:
tensor_a%tensor_b

tensor([1, 2, 3, 4])

In [13]:
torch.remainder(tensor_a,tensor_b)

tensor([1, 2, 3, 4])

In [14]:
torch.pow(tensor_a,tensor_b)

tensor([    1,    64,  2187, 65536])

In [15]:
#another way to write long hand

tensor_a.add(tensor_b)

tensor([ 6,  8, 10, 12])

In [16]:
tensor_a


tensor([1, 2, 3, 4])

In [17]:
tensor_a.add_(tensor_b)

tensor([ 6,  8, 10, 12])